version: '3.9'

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DATABASE_URL=postgres://admin:123456@localhost:5432/rinhabackenddb
      - PORT=8000
    network_mode: host
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "125mb"

  api02:
    <<: *api
    environment:
      - DATABASE_URL=postgres://admin:123456@localhost:5432/rinhabackenddb
      - PORT=8001
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100mb"

  db:
    image: postgres:latest
    hostname: db
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhabackenddb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
