version: '3.9'

services:
  postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=2024
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhabackenddb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
