version: '3.9'

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DATABASE_URL=postgres://admin:123456@localhost:5432/rinhabackenddb
      - PORT=8000
    network_mode: host
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

  api02:
    <<: *api
    environment:
      - DATABASE_URL=postgres://admin:123456@localhost:5432/rinhabackenddb
      - PORT=8001
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhabackenddb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "440MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
